"""
Django settings for stronghold project.

Generated by 'django-admin startproject' using Django 2.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(
    os.path.abspath(__file__))))

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = ''

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = []


# Application definition

DJANGO_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

THIRD_PARTY_APPS = [
    'sass_processor',
]

PROJECT_APPS = [
    'game',
]

INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + PROJECT_APPS

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'stronghold.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'stronghold.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static_root/')

SASS_PROCESSOR_ROOT = STATIC_ROOT

STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'sass_processor.finders.CssFinder',
]


# Puzzle settings
PUZZLE_ORDER = [
    'rot13',
    'sky',
    'image',
    'terminal',  # Requires hard-coding the next puzzle
    'redirect',
    'pages',
    'login',
    'audio_spectrum',
    'vigenere',
    'finish',
]
INSTALLED_APPS += PUZZLE_ORDER

PUZZLE_IMAGE_FONT_NAME = 'Roboto/Roboto-Black.ttf'
PUZZLE_IMAGE_FONT_SIZE = 550
PUZZLE_IMAGE_FILL = (255, 255, 255, 2)

PUZZLE_AUDIO_SPECTRUM_FONT_NAME = 'Roboto/Roboto-Black.ttf'
PUZZLE_AUDIO_SPECTRUM_FONT_SIZE = 150
PUZZLE_AUDIO_SPECTRUM_MIN_FREQ = 14000
PUZZLE_AUDIO_SPECTRUM_MAX_FREQ = 17000
PUZZLE_AUDIO_SPECTRUM_PPS = 30  # Pixels per second
PUZZLE_AUDIO_SPECTRUM_AUDIO_POS = 5000
PUZZLE_AUDIO_SPECTRUM_AUDIO_GAIN = -35
PUZZLE_AUDIO_SPECTRUM_TAGS = {
    'ARTIST': ['SFI'],
    'ALBUM': ['Foreign Battle'],
    'TITLE': ['Deadly Fox'],
    'DATE': ['2019'],
    'TRACKNUMBER': ['9/11'],
    'COMMENT': ['000000A5 000000CC 000096C2 00000022 0000C9EE 0000006A'],
}
