version: 2

updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: monthly
    groups:
      dependencies:
        update-types:
          - minor
          - patch

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: monthly
    groups:
      dependencies:
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      dependencies:
        patterns:
          - "*"
