# Generated by Django 2.1.7 on 2019-02-28 00:20
from django.conf import settings
from django.db import migrations
from django.utils import timezone

from game.puzzles.order import get_puzzle_url


def put_puzzle_data(apps, schema_editor):
    Puzzle = apps.get_model('game', 'Puzzle')
    Puzzle.objects.all().delete()

    end = False
    for id, puzzle in enumerate(settings.PUZZLE_ORDER, 1):
        Puzzle(pk=id, url=get_puzzle_url(puzzle), name=puzzle,
               date=timezone.now()).save()

        if end:
            break
        elif puzzle == 'pages':
            end = True
            # End after putting one puzzle coming after "pages"


class Migration(migrations.Migration):
    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(put_puzzle_data)
    ]
